# This the theme configuration for Docsy.
# Allowed configuration in a theme is (currently):
# params (global and per language)
# menu (global and per language)
# outputformats and mediatypes

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]

[params.drawio]
enable = true
#drawio_server = "https://example.com/"

# For a full list of parameters used in Docsy sites, see:
# https://github.com/google/docsy-example/blob/master/config.toml


[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "_print"
permalinkable = false

[module]
_merge = "deep"
# mount user guide so that we can copy it to skeleton site
[[module.mounts]]
  source = "userguide"
  target = "assets/userguide"
[[module.mounts]]
  source = "assets/bootstrap/scss/vendor"
  target = "assets/bootstrap/scss/vendor"
[[module.mounts]]
  source = "assets/bootstrap/scss/"
  target = "assets/bootstrap/scss/"
[[module.mounts]]
  source = "assets/bootstrap/"
  target = "assets/bootstrap/"
[[module.mounts]]
  source = "assets/vendor/bootstrap/scss/vendor"
  target = "assets/vendor/bootstrap/scss/vendor"
#[[module.mounts]]
#  source = "assets/vendor/bootstrap/scss/"
#  target = "assets/vendor/bootstrap/scss/"
#[[module.mounts]]
#  source = "assets/vendor/bootstrap/"
#  target = "assets/vendor/bootstrap/"
#[[module.mounts]]
#  source = "assets/vendor/"
#  target = "assets/vendor/"
# mount assets directory
[[module.mounts]]
  source = "assets"
  target = "assets"
# work around https://github.com/golang/go/issues/37397
# mount i18n directory
[[module.mounts]]
  source = "i18n"
  target = "i18n"
# mount layouts directory
[[module.mounts]]
  source = "layouts"
  target = "layouts"
# mount static directory
[[module.mounts]]
  source = "static"
  target = "static"
# Dependencies are brought in as modules
# and mount points are declared
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/bootstrap/scss"
[[module.mounts]]
  source = "assets/bootstrap/scss/vendor"
  target = "assets/vendor/bootstrap/scss/vendor"

[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/Font-Awesome/scss"
